version: '3.8'

services:
  app:
    build:
      context: .
    container_name: gadget_shop_backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}" 
    env_file:
      - .env
    volumes:
      - .:/app 
      - /app/node_modules 
    command: npm run start:dev # Use the dev command for hot reloading
    depends_on:
      - redis
    networks:
      - app-network

  worker:
    build:
      context: .
    container_name: gadget_shop_worker
    restart: unless-stopped
    command: npm run start:worker
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7.0
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
